### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "josefa@gmail.com",
    "password": "Jureminha"
}

### Find a particular user with a given email
GET http://localhost:3000/auth?email=licalegal@gmail.com

### Find a particular user with a given id
GET http://localhost:3000/auth/30

### Update a user
PATCH http://localhost:3000/auth/6
content-type: application/json

{
    "email": "ligia@gmail.com"
}

### Delete a user with a given id
DELETE http://localhost:3000/auth/6

